/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fithealthteam.fithealth.huawei.CloudDB;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType Exercise.
 *
 * @since 2021-08-13
 */
@PrimaryKeys({"id"})
public final class Exercise extends CloudDBZoneObject {
    private String id;

    private String exerciseType;

    @DefaultValue(booleanValue = false)
    private Boolean completeStatus;

    private Double calories;

    private Date date;

    private String user_id;

    public Exercise() {
        super(Exercise.class);
        this.completeStatus = false;
    }

    public Exercise(String exerciseType, Double calories, boolean completeStatus) {
        super(Exercise.class);
        this.exerciseType = exerciseType;
        this.calories = calories;
        this.completeStatus = completeStatus;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType;
    }

    public String getExerciseType() {
        return exerciseType;
    }

    public void setCompleteStatus(Boolean completeStatus) {
        this.completeStatus = completeStatus;
    }

    public Boolean getCompleteStatus() {
        return completeStatus;
    }

    public void setCalories(Double calories) {
        this.calories = calories;
    }

    public Double getCalories() {
        return calories;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getDate() {
        return date;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_id() {
        return user_id;
    }

}
