/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fithealthteam.fithealth.huawei.CloudDB;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType exercise.
 *
 * @since 2021-08-15
 */
@PrimaryKeys({"id", "uid"})
public final class exercise extends CloudDBZoneObject {
    private Integer id;

    private String uid;

    private String exerciseType;

    private Double calories;

    @DefaultValue(booleanValue = false)
    private Boolean completeStatus;

    private Date date;

    @DefaultValue(booleanValue = false)
    private Boolean deleteStatus;

    public exercise() {
        super(exercise.class);
        this.completeStatus = false;
        this.deleteStatus = false;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid() {
        return uid;
    }

    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType;
    }

    public String getExerciseType() {
        return exerciseType;
    }

    public void setCalories(Double calories) {
        this.calories = calories;
    }

    public Double getCalories() {
        return calories;
    }

    public void setCompleteStatus(Boolean completeStatus) {
        this.completeStatus = completeStatus;
    }

    public Boolean getCompleteStatus() {
        return completeStatus;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getDate() {
        return date;
    }

    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    public Boolean getDeleteStatus() {
        return deleteStatus;
    }

}
